version: '3'
services:
  myphp:
    build: ./php
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - "/Users/narupol.bal/www:/var/www/html"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /Users/narupol.bal/db/mysqldb:/var/lib/mysql
      - /Users/narupol.bal/db/mysql-schema:/docker-entrypoint-initdb.d
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CyoiydgTv